
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getDicitionary } from "@/dictionary";
import StoreProvider from "../Storeprovider";
import AppLayout from "../AppLayout";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: { lang: 'en' | 'ar' }
}) {

  const awaitedParams = await params

  const dictionary = await getDicitionary(awaitedParams.lang)


  return (
    <html lang={awaitedParams.lang} dir={awaitedParams.lang === 'ar' ? 'rtl' : 'ltr'}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <AppLayout dictionary={dictionary} >
            {children}
          </AppLayout>
        </StoreProvider>
      </body>
    </html>
  );
}
